### ISSUE TITLE
can't download the file

### ISSUE THREAD

**Issue by jdnielss** [r0ld3x/terabox-app#9]
```
{
    "category": "6",
    "fs_id": "703910572608217",
    "isdir": "0",
    "local_ctime": "1695060410",
    "local_mtime": "1695060427",
    "md5": "2ab821f50a05549d2c4443131d3d2113",
    "path": "/Test.zip",
    "play_forbid": "0",
    "server_ctime": "1695062520",
    "server_filename": "Test.zip",
    "server_mtime": "1695132742",
    "size": "1384683522",
    "emd5": "0b2611faaj13ec1a1c1e6474a5ef8efc"
}
```

Maybe their response has been changed?

**Comment by r0ld3x** [comment]
did you changed cookies?

**Comment by jdnielss** [comment]
No, i just run you project

i dont change the code

**Comment by r0ld3x** [comment]
check readme.md and fill the cookies

**Comment by jdnielss** [comment]
get this error 

![image](https://github.com/r0ld3x/terabox-app/assets/28420302/43ecadb5-4050-4a5f-991c-ed271a1a8451)

**Comment by sistematod** [comment]
help error

**Comment by r0ld3x** [comment]
Api is dead

**Comment by jatinkumar31** [comment]
Can u fix it please?

**Comment by sistematod** [comment]
help help please Can u fix it please?

**Comment by sistematod** [comment]
![err workers](https://github.com/r0ld3x/terabox-app/assets/121248957/ea038cc0-6fbc-451d-85fb-ea3650b9b2db)
![vercel error](https://github.com/r0ld3x/terabox-app/assets/121248957/414b0db8-dad3-44fd-b1f9-175be49f894d)

**Comment by Bharaththop** [comment]
Can you please give me the URL of final api call ?

**Comment by r0ld3x** [comment]
> Can you please give me the URL of final api call ?

`https://afca-174-138-88-233.ngrok-free.app?get?url=url`

**Comment by r0ld3x** [comment]
> ![err workers](https://private-user-images.githubusercontent.com/121248957/299829328-ea038cc0-6fbc-451d-85fb-ea3650b9b2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzI4LWVhMDM4Y2MwLTZmYmMtNDUxZC04NWZiLWVhMzY1MGI5YjJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ4NzY5ZWJkYjg4ZThhODkyYWVhODZiOWM0OThlMWVlZjNiZTc5NTVlZTQ3NTBkZmQxYzQyNTRmNDk4OTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e1ydp_0kGcBbeooJI9Jkiwms3zN2ymtVqF7ECsA6tj4) ![vercel error](https://private-user-images.githubusercontent.com/121248957/299829338-414b0db8-dad3-44fd-b1f9-175be49f894d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzM4LTQxNGIwZGI4LWRhZDMtNDRmZC1iMWY5LTE3NWJlNDlmODk0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDVmMGMwNTRmMmQ4YTc1NGU3MTgyNjIxY2FlZmI1MTUyMTk1NWQ4N2UzYWJhNjE3NzIzNzI0ZmQ0YTkxMmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZP864ZNfUjzTWZD-5z-2mq1gCEcXkWWndGXAkMGRBV4)

its fixed now check again

**Comment by sistematod** [comment]
> > ![errar trabajadores](https://private-user-images.githubusercontent.com/121248957/299829328-ea038cc0-6fbc-451d-85fb-ea3650b9b2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzI4LWVhMDM4Y2MwLTZmYmMtNDUxZC04NWZiLWVhMzY1MGI5YjJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ4NzY5ZWJkYjg4ZThhODkyYWVhODZiOWM0OThlMWVlZjNiZTc5NTVlZTQ3NTBkZmQxYzQyNTRmNDk4OTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e1ydp_0kGcBbeooJI9Jkiwms3zN2ymtVqF7ECsA6tj4) ![error de vercel](https://private-user-images.githubusercontent.com/121248957/299829338-414b0db8-dad3-44fd-b1f9-175be49f894d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzM4LTQxNGIwZGI4LWRhZDMtNDRmZC1iMWY5LTE3NWJlNDlmODk0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDVmMGMwNTRmMmQ4YTc1NGU3MTgyNjIxY2FlZmI1MTUyMTk1NWQ4N2UzYWJhNjE3NzIzNzI0ZmQ0YTkxMmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZP864ZNfUjzTWZD-5z-2mq1gCEcXkWWndGXAkMGRBV4)
> 
> Ya está arreglado, vuelve a comprobarlo.

![Screenshot_49](https://github.com/r0ld3x/terabox-app/assets/121248957/76ace0d0-b672-4447-bf5f-209631e29173)

**Comment by r0ld3x** [comment]
> > > ![errar trabajadores](https://private-user-images.githubusercontent.com/121248957/299829328-ea038cc0-6fbc-451d-85fb-ea3650b9b2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzI4LWVhMDM4Y2MwLTZmYmMtNDUxZC04NWZiLWVhMzY1MGI5YjJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ4NzY5ZWJkYjg4ZThhODkyYWVhODZiOWM0OThlMWVlZjNiZTc5NTVlZTQ3NTBkZmQxYzQyNTRmNDk4OTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e1ydp_0kGcBbeooJI9Jkiwms3zN2ymtVqF7ECsA6tj4) ![error de vercel](https://private-user-images.githubusercontent.com/121248957/299829338-414b0db8-dad3-44fd-b1f9-175be49f894d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzM4LTQxNGIwZGI4LWRhZDMtNDRmZC1iMWY5LTE3NWJlNDlmODk0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDVmMGMwNTRmMmQ4YTc1NGU3MTgyNjIxY2FlZmI1MTUyMTk1NWQ4N2UzYWJhNjE3NzIzNzI0ZmQ0YTkxMmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZP864ZNfUjzTWZD-5z-2mq1gCEcXkWWndGXAkMGRBV4)
> > 
> > 
> > Ya está arreglado, vuelve a comprobarlo.
> 
> ![Screenshot_49](https://private-user-images.githubusercontent.com/121248957/304746327-76ace0d0-b672-4447-bf5f-209631e29173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjUwNTAsIm5iZiI6MTcwNzkyNDc1MCwicGF0aCI6Ii8xMjEyNDg5NTcvMzA0NzQ2MzI3LTc2YWNlMGQwLWI2NzItNDQ0Ny1iZjVmLTIwOTYzMWUyOTE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxNTMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGFjZjRlYzVhMjVlZTYxMzIwOWRlYWFlZGMwZjFiNTRkNTk2NzUxNDE5MTY4MTk0N2ZlM2YyNTY1YmU5NmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uyBZBNJdIxVzyeN69ICgXjxfHJdBSdGWTA_-Prz0nJY)


only direct media supports this time like videos not folder.

**Comment by sistematod** [comment]
> > > > ![errar trabajadores](https://private-user-images.githubusercontent.com/121248957/299829328-ea038cc0-6fbc-451d-85fb-ea3650b9b2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzI4LWVhMDM4Y2MwLTZmYmMtNDUxZC04NWZiLWVhMzY1MGI5YjJkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ4NzY5ZWJkYjg4ZThhODkyYWVhODZiOWM0OThlMWVlZjNiZTc5NTVlZTQ3NTBkZmQxYzQyNTRmNDk4OTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e1ydp_0kGcBbeooJI9Jkiwms3zN2ymtVqF7ECsA6tj4) ![error de vercel](https://private-user-images.githubusercontent.com/121248957/299829338-414b0db8-dad3-44fd-b1f9-175be49f894d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjQyMzQsIm5iZiI6MTcwNzcyMzkzNCwicGF0aCI6Ii8xMjEyNDg5NTcvMjk5ODI5MzM4LTQxNGIwZGI4LWRhZDMtNDRmZC1iMWY5LTE3NWJlNDlmODk0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDVmMGMwNTRmMmQ4YTc1NGU3MTgyNjIxY2FlZmI1MTUyMTk1NWQ4N2UzYWJhNjE3NzIzNzI0ZmQ0YTkxMmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZP864ZNfUjzTWZD-5z-2mq1gCEcXkWWndGXAkMGRBV4)
> > > 
> > > 
> > > Ya está arreglado, vuelve a comprobarlo.
> > 
> > 
> > ![Captura de pantalla_49](https://private-user-images.githubusercontent.com/121248957/304746327-76ace0d0-b672-4447-bf5f-209631e29173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjUwNTAsIm5iZiI6MTcwNzkyNDc1MCwicGF0aCI6Ii8xMjEyNDg5NTcvMzA0NzQ2MzI3LTc2YWNlMGQwLWI2NzItNDQ0Ny1iZjVmLTIwOTYzMWUyOTE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxNTMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGFjZjRlYzVhMjVlZTYxMzIwOWRlYWFlZGMwZjFiNTRkNTk2NzUxNDE5MTY4MTk0N2ZlM2YyNTY1YmU5NmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uyBZBNJdIxVzyeN69ICgXjxfHJdBSdGWTA_-Prz0nJY)
> 
> Esta vez solo se admiten medios directos, como videos, no carpetas.


It still shows the error and I am downloading a simple .mp4

Link de prueba:https://terabox.com/s/1WqMVPJtTeGSByPz4ZCTWvA

![image](https://github.com/r0ld3x/terabox-app/assets/121248957/42c19ab4-b8aa-42ce-ae21-e44baf0732c8)

**Comment by r0ld3x** [comment]
some links dont work properly so its better leave it
